// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhEQHBT7H2kdilNQP-0O2BGldQykBFRG8',
    appId: '1:115671221857:web:1beafda7a8985fb00b8c20',
    messagingSenderId: '115671221857',
    projectId: 'chat-app-4d192',
    authDomain: 'chat-app-4d192.firebaseapp.com',
    storageBucket: 'chat-app-4d192.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfmHuib-EXVeA5pBoGCmD7NwWnjgSuGsE',
    appId: '1:115671221857:android:f8ba6ca0f61cb5720b8c20',
    messagingSenderId: '115671221857',
    projectId: 'chat-app-4d192',
    storageBucket: 'chat-app-4d192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG7K86soAwxYAWBkicl7mFQSSYJpvqicA',
    appId: '1:115671221857:ios:7620778b1c23bb2b0b8c20',
    messagingSenderId: '115671221857',
    projectId: 'chat-app-4d192',
    storageBucket: 'chat-app-4d192.firebasestorage.app',
    iosBundleId: 'com.example.flutterChallengeEn01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG7K86soAwxYAWBkicl7mFQSSYJpvqicA',
    appId: '1:115671221857:ios:7620778b1c23bb2b0b8c20',
    messagingSenderId: '115671221857',
    projectId: 'chat-app-4d192',
    storageBucket: 'chat-app-4d192.firebasestorage.app',
    iosBundleId: 'com.example.flutterChallengeEn01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhEQHBT7H2kdilNQP-0O2BGldQykBFRG8',
    appId: '1:115671221857:web:cb1e8f9fcf3d45860b8c20',
    messagingSenderId: '115671221857',
    projectId: 'chat-app-4d192',
    authDomain: 'chat-app-4d192.firebaseapp.com',
    storageBucket: 'chat-app-4d192.firebasestorage.app',
  );
}
