import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure
import 'app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  
  // Initialize Firebase with options generated by flutterfire CLI
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  
  // Ensure Firestore network is enabled for real-time updates
  // Firestore persistence is enabled by default on mobile platforms
  try {
    await FirebaseFirestore.instance.enableNetwork();
  } catch (e) {
    // Network may already be enabled, ignore error
    debugPrint('Firestore network: $e');
  }
  
  runApp(const ProviderScope(child: MyApp()));
}
